spring:
  application:
    name: "data-collector"
    process-id: 1141
bss:
  url: "http://localhost"
  port: 8585
config:
  source:
    type: "rest"
authentication:
  username: "FARZAD"
  password: "fja123"
  service: ""

