spring:
  application:
    name: "data-collector"

system:
  info:
    device-type: "server"
    os: "linux"
    browser: ""
    channel-id: 1006
    channel-version: "1.0"
    device-id: ""
    system-id: 1001
    business-center-id: 1001
    technologies: []
    language-code: "EN"
    partner-domain: ""
    partner-token: ""
application:
  info:
    process-id: 1141

authentication:
  info:
    username: "FARZAD"
    password: "fja123"
    service: ""

bss:
  url: "http://localhost"
  port: 8585
config:
  source:
    type: "rest"


