spring:
  application:
    name: data-collector
  datasource:
    data-collector:
      url: jdbc:h2:mem:data-collector-db
      driver-class-name: org.h2.Driver
      username: DATA_COLLECTOR
      password:
      liquibase:
        change-log: classpath:db-changes/db.changelog-master.xml
        contexts: schema-creation, table-creation, sequence-creation
        drop-first: true
        enabled: true
        password:
        url: jdbc:h2:mem:data-collector-db
        user: DATA_COLLECTOR
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

config:
  source:
    type: db
    rest:
      url: localhost
      port: 8585
      path: /config

